export const GET_LATEST_MOVIES = 'GET_LATEST_MOVIES';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const MOVIE_ERROR = 'MOVIE_ERROR';

export const GET_EVENTS = 'GET_EVENTS';
export const EVENT_ERROR = 'EVENT_ERROR';

export const SELECT_SEATS = 'SELECT_SEATS';
export const SET_TICKET_TYPE = 'SET_TICKET_TYPE';
export const COMPLETE_BOOKING = 'COMPLETE_BOOKING';
export const RESET_BOOKING = 'RESET_BOOKING';